
[[main]]
  name = "The Consortium"
  identifier = "the_consortium"
  url = ""
  weight = "10"

[[main]]
  name = "About"
  identifier = "about"
  url = "#about"
  weight = "11"
  parent = "the_consortium"

[[main]]
  name = "Support"
  identifier = "support"
  url = "#support"
  weight = "12"
  parent = "the_consortium"

[[main]]
  name = "Get Involved"
  url = "#get_involved"
  weight = "13"
  parent = "the_consortium"

[[main]]
  name = "Letters"
  identifier = "letters"
  weight = "20"

[[main]]
  name = "Moratorium Letter"
  identifier = "moratorium_letter"
  url = "moratorium_letter"
  weight = "21"
  parent = "letters"

[[main]]
  name = "Reports"
  identifier = "reports"
  url = ""
  weight = "30"

[[main]]
  name = "Hexachloroethane"
  url = "/hc/"
  weight = "31"
  parent = "reports"


[[main]]
  name = "Munitions"
  url = ""
  identifier = "munitions"
  weight = "40"


[[main]]
  name = "Munitions Library"
  url = "/munitions_library/"
  parent = "munitions"
  weight = "41"

[[main]]
  name = "Submit Munitions Photos"
  parent = "munitions"
  url = "/munition_submission/"
  weight = "42"


[[main_right]]
  url = "/contact/"
  name = "<i class='far fa-envelope'></i>"
  identifier = "email"
  weight = 1

[[main_right]]
  url = "https://www.github.com/chemicalweaponsresearch"
  name = "<i class='fab fa-github-alt'></i>"
  identifier = "github"
  weight = 2

[[main_right]]
  url = "https://www.twitter.com/chemweaponsci"
  name = "<i class='fab fa-twitter'></i>"
  identifier = "twitter"
  weight = 3