---
title: "Open Letter to Halt Use of Chemical Weapons"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: false
    toc_float: false
---

<br>

Dear American Elected Officials,

We, the undersigned members of the scientific community, request that you leverage any and all avenues to ***halt current and future use of chemical weapons*** against civilians.

The use of chemical weapons (such as [tear gas](https://en.wikipedia.org/wiki/Tear_gas) and [munition smoke](https://en.wikipedia.org/wiki/Hexachloroethane)) constitutes an indiscriminate application of toxic materials to a non-consenting population and the environment with short and long-term consequences for both. 

By their very nature, [chemical weapons](https://en.wikipedia.org/wiki/Chemical_weapon) include compounds designed to [interact](https://en.wikipedia.org/wiki/Chemical_reaction) with components of their environment, including humans.
These fundamentally reactive compounds significantly impact [human health and well-being in the short and long-term](https://www.dontshootpdx.org/riot-control-agents-report/).
However, their impacts are not limited to humans and can have significant [ecological consequences](https://www.cbc.ca/radio/asithappens/how-norwegian-trees-tell-the-story-of-a-cloaked-nazi-war-ship-1.4616295).
Additionally, disbursement of many of these compounds into the environment without remediation constitutes [illegal disposal of hazardous wastes under the Environmental Protection Act](https://www.epa.gov/hw/learn-basics-hazardous-waste).


First-hand accounts and collected munitions indicate that such weapons are often deployed without regard to explicitly labeled disbursement requirements, such as ["use only outdoors"](https://www.oregonlive.com/crime/2020/07/downtown-jail-inmates-hitting-panic-buttons-due-to-tear-gas-wafting-into-cells-lawyers-say.html), ["use from at least a minimal safe distance"](https://www.cosmopolitan.com/politics/a33450374/black-lives-matter-protests-portland-oregon-stormtroopers-federal-agents/), and ["use only within 5 years of the manufacture date"](https://www.portlandmercury.com/blogtown/2020/08/04/28698841/protesters-and-lawmakers-are-concerned-about-the-effects-of-expired-tear-gas).
Using chemical weapons in such situations puts human lives in significant risk.

Presently, however, law enforcement is functionally allowed to use chemical weapons against civilians [without consequence](https://www.kptv.com/news/study-tracks-use-of-tear-gas-as-portland-nears-70-days-of-protests/article_963a57c6-d6a8-11ea-93b6-df94059985fc.html).
Further, private industry is allowed to [manufacture munitions](https://www.defense-technology.com/product/maximum-smoke-hc-large-style-canister/) for law enforcement using known aquatic toxins and probable human carcinogens, while providing incomplete documentation of components and risks.
Given the obfuscation of components, indiscriminate nature, and reactivity of chemical weapons, victims of their impacts are not able to readily obtain information about what weapons were used and in what condition they were deployed.
Instead, they are forced to first identify the chemicals used on them via forensics and then determine their consequences.
Even if indications are strong that the chemicals are more noxious than law enforcement states, including carcinogenicity, agencies can continue to use the chemical weapons until they are *proven toxic*.

Leveraging of this "assumed safe" loophole as a tactical approach against protesters amounts to chemical experimentation on humans.
Given that the recipient population (including bystanders) is not able to determine fundamentally how it is impacted by the munitions and individuals may not be able to leave areas made unsafe, the use of chemical weapons by any state against its people is an act of domestic terrorism. 

***As professionals who hold basic ethical standards for [the use of human subjects in experimental trials](https://www.fda.gov/patients/clinical-trials-what-patients-need-know/informed-consent-clinical-trials) and [treatment of the environment](https://www.epa.gov/node/127431_), we insist that you do as well.***

We specifically demand the following:

1. A complete moratorium on chemical weapons being used on humans in the United States. 
2. Full dismantling and proper disposal of law enforcement chemical weapons caches.
3. The legal default being set such that a chemical is not to be used and evidence must be provided of its safety before base consideration ("assumed toxic").
4. Potential chemical weapons must undergo the same review as chemicals involved in [agricultural applications](https://www.fda.gov/food/chemicals-metals-pesticides-food/chemicals).
5. They must also undergo a further review to specifically address use *against* humans.

Swiftly enacting this platform will help save human lives, reduce negative impacts on the environment, and counter-act fascism.

<br>

With best regards,

<br>

**Author**

Dr. Juniper L. Simonis, they/them; [DAPPER Stats](https://www.dapperstats.com), Founder & Lead Scientist

<br>

**Cosignatories**

William Booker, he/him; Florida State University, PhD Candidate  
Dr. Sara Garnett, she/her; Michigan State University, Research Associate  
Helen Caddes, she/her; Musician / Digital Media Specialist  
Dr. Maryam Zaringhalam, she/her; 500 Women Scientists, Leadership Member  
Russ Dial, he/him; Pierce County Master Gardener,Chemical weapons are toxic to plants as well as humans  
Dr Jamie Uhrig, they; Staff Physician, Correctional Health Services, New York City Health + Hospitals  
Kade McVay, he/him; Broomshire Unlimited, Co-founder  
Gail Stonebarger, she/her; OHSU Behavioral Neuroscience graduate researcher, PhD candidate  
Dr. Jonathan Walter, he/him; Ronin Institute for Independent Scholarship, Research Scholar  
Dr. Kelly Ramirez, she/her; 500 Women Scientists, Co-Founder; Assistant Professor, UTEP  
Dr. Karen Dyson, she/her; Dendrolytics Lab; Founder  
Dr Alex Bond, he/him; University of Tasmania & University of the Highlands & Islands  
Sarah E Myhre PhD, she/her; Rowan Institute, ED	Kavli Fellow with the National Academy of Science, Engineering, and Medicine  
Dr.Teresa Swanson, she/her; Research Scientist, Miller Lab, Univ. of Washington  
Heather Price, PhD, she/her; Atmospheric Chemist, Air pollution and climate researcher and educator  
Amberlie Barnard, she/her; VR Analytical, Chemist II  
Dr. Travis Hinkelman, he/him; Environmental Science Associates, Senior Data Scientist  
Jeremy B Yoder, he/him; CSU Northridge, Assistant Professor of Biology  
Jeffrey Letourneau, he/him; Duke University, PhD Candidate	NSF GRFP Fellow  
Kristina Bissonette, she/her
Dr. Cathleen Fry, she/they; LANL, Agnew National Security Postdoctoral Fellow  
Dr. Justin Colacino, he/him; University of Michigan, John G. Searle Assistant Professor of Environmental Health Sciences; 2019-20 President of the Michigan Regional Chapter of the Society of Toxicology  
Jessica Velez, she/her; University of Tennessee Knoxville, Graduate Research Assistant	
Dr. Brendan J. Pinto, he/him; University of Texas at Austin, Department of Integrative Biology, Postdoctoral Researcher; Milwaukee Public Museum, Research Associate  
Dr. Maleah Paisley, she; Medical Laboratory Scientist  
Zoey Werbin, she/her; Boston University, PhD Student; National Science Foundation Graduate Fellow  
Dr Leslie New, she/her; Washington Stats University Vancouver, Assistant Professor  
Lauren Edwards, she/her; 500 Women Scientists, Executive Leadership	 
Ira Kraemer, they/them; Graduate Student in Neuroscience  
Dr. Hao Ye, he/him; University of Florida, Health Science Center Libraries   
Dr. Maleah Paisley, She; Medical Laboratory Scientist   
Dr. Ethan White, he/him; University of Florida  
Dr. Rebecca Barnes, she/her; Colorado College, Associate Professor of Environmental Science  
David Dayan, PhD, he/him; Oregon State University  
Charise Johnson, she/her; British Academy, Policy Advisor  
Dr. Emily Rollinson, she/her; East Stroudsburg University, Assistant Professor of Biology  
Sahana Kuthyar, she/her; UC San Diego, Graduate Student  
Jessica Sido, PhD, She/Her; Senior Scientist   
EBeil, She/Her; Art Educator & Color Scientist   
Dr. Julia Maresca, She/her; University of Delaware, Associate Professor   
Dr. Gretchen Goldman, she/her; 500 Women Scientists, Leadership Board Member  
Dr. Loren Cassin Sackett, She/her; Assistant Professor, University of Louisiana  
Kelly Mistry, She/her; Graduate student  
Dr. Glenda Yenni, she/her; University of Florida  
Elizabeth Mohr, She/her; Montana State University, Ph.D. Candidate  
Dr. Morgan Ernest, she/her; Associate Professor  
Dr. Alejandra Maldonado, she/her; Toxicologist  
Jessica O’Neill, she/her; University at Buffalo, Doctoral candidate, American Public Health Association Policy Institute student scholar; Co-founder of Buffalo, NY 500 Women Scientists  
Dr. Valérie Vilmont, she/her; CHUV -Clinical Scientist  
Msc. Melissa Mendes, she/her; McGill University, PhD Candidate  
Morgan Malone, she/her; Graduate Student  
Ceri Jensen, she/her; Engineer  
Dr. Sara Winings, she/her; PharmD  
Dr. Stephanie Fronk, she/her; Process engineer  
Amika Savage, MN, APRN, FNP-BC, CHES, she/they; Oregon Health & Science University, Doctoral Student  
Dr. Gloria Tavera, she/hers; Case Western Reserve University, PhD, MD Candidate  
Nina Damm, she/her; Washington State University, PhD student  
Emily Sutton, she/her; University of Oregon, PhD candidate  
K Danowski, she/her; retired  
Dr. A.L. Carter, they/them/theirs; Sage Grant Writing, Founder & Lead Consultant  
Zachary Wilson, he/him; Information Systems Engineer  
Jacob Rose, he/him; Brown University, PhD student in Electrical & Computer Engineering  
Amelia Abreu, she/her; UX Night School, Teacher and Researcher, Founder  
Hazel Anderson, she/her; Michigan State University, Undergraduate Student  
Megan Lynch, she/her; UC Davis, Masters student  
Loretta Koll, M.Ed., she/her; Educator  

<br>

version 0.0.2 2020-08-10

[Add your name](https://forms.gle/U2h1rZFdPxouW4SFA) to the list of signatories.

[Archived version](https://doi.org/10.5281/zenodo.3978769) of the letter.

<br>