title = "Chemical Weapons Research Center"
baseurl = "https://www.chemicalweaponsresearch.com/"
copyright = "Chemical Weapons Research Center {year}"

enableGitInfo = false

defaultContentLanguage = "en"
hasCJKLanguage = false  
defaultContentLanguageInSubdir = false
removePathAccents = true

summaryLength = 30  
paginate = 10  
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableAliases = true  

[permalinks]
  authors = "/author/:slug/"
  tags = "/tag/:slug/"
  categories = "/category/:slug/"
  publication_types = "/publication-type/:slug/"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest", "headers", "redirects" ]
  section = [ "HTML", "RSS" ]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  
  [markup.highlight]
    codeFences = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 75
  anchor = "smart"  

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  publication_type = "publication_types"

# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 70.0

[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"


[[params.social]]
  icon = "envelope"
  icon_pack = "fab"
  link = "mailto:contact@dapperstats.com"

[[params.social]]
  icon = "twitter"
  icon_pack = "fab"
  link = "//twitter.com/dapperstats"

[[params.social]]
  icon = "github"
  icon_pack = "fab"
  link = "//github.com/dapperstats"